BEGIN;

CREATE TEMP TABLE temp_etudiants_demo_vote_upc (
    faculte_code TEXT,
    promotion_code TEXT,
    departement_code TEXT,
    departement_nom TEXT,
    matricule TEXT,
    nom TEXT,
    post_nom TEXT,
    prenom TEXT,
    date_naissance TEXT,
    lieu_naissance TEXT,
    sexe TEXT,
    email TEXT
) ON COMMIT DROP;

INSERT INTO temp_etudiants_demo_vote_upc (
    faculte_code,
    promotion_code,
    departement_code,
    departement_nom,
    matricule,
    nom,
    post_nom,
    prenom,
    date_naissance,
    lieu_naissance,
    sexe,
    email
)
VALUES
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/001', 'KABAMBA', 'KABONGO', 'SOPHIA', '1999-02-02', 'KINSHASA', 'F', 'sophia.kabamba.001@gmail.com'),
    ('FASE', 'L1', 'GESTION', 'GESTION', 'UPC/FASE/L1/002', 'ILUNGA', 'MUTOMBO', 'JEAN', '2000-03-03', 'LUBUMBASHI', 'M', 'jean.ilunga.002@gmail.com'),
    ('MEDECINE', 'G0', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/G0/003', 'TSHIMANGA', 'MBUYI', 'GRACE', '2001-04-04', 'KANANGA', 'F', 'grace.tshimanga.003@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L1/004', 'MUTOMBO', 'KALONJI', 'JONATHAN', '2002-05-05', 'MATADI', 'M', 'jonathan.mutombo.004@gmail.com'),
    ('THEOLOGIE', 'L1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L1/005', 'KALONJI', 'KAMBALE', 'SARAH', '2003-06-06', 'MBUJI-MAYI', 'F', 'sarah.kalonji.005@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/006', 'KASONGO', 'KASONGO', 'CEDRIC', '2004-07-07', 'KISANGANI', 'M', 'cedric.kasongo.006@gmail.com'),
    ('FASE', 'L2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L2/007', 'LUKUSA', 'ILUNGA', 'CHRISTELLE', '2005-08-08', 'KIKWIT', 'F', 'christelle.lukusa.007@gmail.com'),
    ('MEDECINE', 'L1', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/L1/008', 'MUKENDI', 'LUKUSA', 'CHRISTIAN', '2006-09-09', 'GOMA', 'M', 'christian.mukendi.008@gmail.com'),
    ('DROIT', 'L2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L2/009', 'KAZADI', 'KANDA', 'FAVEUR', '2007-10-10', 'KINSHASA', 'F', 'faveur.kazadi.009@gmail.com'),
    ('THEOLOGIE', 'L2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L2/010', 'MBUYI', 'MULUMBA', 'MOISE', '1998-11-11', 'LUBUMBASHI', 'M', 'moise.mbuyi.010@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/011', 'TSHIBANGU', 'MBALA', 'CLAUDIA', '1999-12-12', 'KANANGA', 'F', 'claudia.tshibangu.011@gmail.com'),
    ('FASE', 'L3', 'FINANCE', 'FINANCE', 'UPC/FASE/L3/012', 'KABUYA', 'NTUMBA', 'PRINCE', '2000-01-13', 'MATADI', 'M', 'prince.kabuya.012@gmail.com'),
    ('MEDECINE', 'L2', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/L2/013', 'KANDA', 'MUKENDI', 'RUTH', '2001-02-14', 'MBUJI-MAYI', 'F', 'ruth.kanda.013@gmail.com'),
    ('DROIT', 'L3', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L3/014', 'MALU', 'KAZADI', 'JUNIOR', '2002-03-15', 'KISANGANI', 'M', 'junior.malu.014@gmail.com'),
    ('THEOLOGIE', 'L3', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L3/015', 'KABONGO', 'KALALA', 'DANIELLA', '2003-04-16', 'KIKWIT', 'F', 'daniella.kabongo.015@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/016', 'NGOY', 'TSHILOMBO', 'EMMANUEL', '2004-05-17', 'GOMA', 'M', 'emmanuel.ngoy.016@gmail.com'),
    ('FASE', 'M1', 'GESTION', 'GESTION', 'UPC/FASE/M1/017', 'LUNDA', 'KABONGO', 'SOPHIA', '2005-06-18', 'KINSHASA', 'F', 'sophia.lunda.017@gmail.com'),
    ('MEDECINE', 'L3', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/L3/018', 'KIKASA', 'MUTOMBO', 'JEAN', '2006-07-19', 'LUBUMBASHI', 'M', 'jean.kikasa.018@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M1/019', 'MAVINGA', 'MBUYI', 'GRACE', '2007-08-20', 'KANANGA', 'F', 'grace.mavinga.019@gmail.com'),
    ('THEOLOGIE', 'M1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M1/020', 'KABASELE', 'KALONJI', 'JONATHAN', '1998-09-21', 'MATADI', 'M', 'jonathan.kabasele.020@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/021', 'MULUMBA', 'KAMBALE', 'SARAH', '1999-10-22', 'MBUJI-MAYI', 'F', 'sarah.mulumba.021@gmail.com'),
    ('FASE', 'M2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/M2/022', 'KAPINGA', 'KASONGO', 'CEDRIC', '2000-11-23', 'KISANGANI', 'M', 'cedric.kapinga.022@gmail.com'),
    ('MEDECINE', 'PR_BACH1', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/PR_BACH1/023', 'KANIKI', 'ILUNGA', 'CHRISTELLE', '2001-12-24', 'KIKWIT', 'F', 'christelle.kaniki.023@gmail.com'),
    ('DROIT', 'M2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/M2/024', 'TSHIAMALA', 'LUKUSA', 'CHRISTIAN', '2002-01-25', 'GOMA', 'M', 'christian.tshiamala.024@gmail.com'),
    ('THEOLOGIE', 'M2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/M2/025', 'KABAMBA', 'KANDA', 'FAVEUR', '2003-02-26', 'KINSHASA', 'F', 'faveur.kabamba.025@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/026', 'ILUNGA', 'MULUMBA', 'MOISE', '2004-03-27', 'LUBUMBASHI', 'M', 'moise.ilunga.026@gmail.com'),
    ('FASE', 'L1', 'FINANCE', 'FINANCE', 'UPC/FASE/L1/027', 'TSHIMANGA', 'MBALA', 'CLAUDIA', '2005-04-01', 'KANANGA', 'F', 'claudia.tshimanga.027@gmail.com'),
    ('MEDECINE', 'BACH2', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/BACH2/028', 'MUTOMBO', 'NTUMBA', 'PRINCE', '2006-05-02', 'MATADI', 'M', 'prince.mutombo.028@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L1/029', 'KALONJI', 'MUKENDI', 'RUTH', '2007-06-03', 'MBUJI-MAYI', 'F', 'ruth.kalonji.029@gmail.com'),
    ('THEOLOGIE', 'L1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L1/030', 'KASONGO', 'KAZADI', 'JUNIOR', '1998-07-04', 'KISANGANI', 'M', 'junior.kasongo.030@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/031', 'LUKUSA', 'KALALA', 'DANIELLA', '1999-08-05', 'KIKWIT', 'F', 'daniella.lukusa.031@gmail.com'),
    ('FASE', 'L2', 'GESTION', 'GESTION', 'UPC/FASE/L2/032', 'MUKENDI', 'TSHILOMBO', 'EMMANUEL', '2000-09-06', 'GOMA', 'M', 'emmanuel.mukendi.032@gmail.com'),
    ('MEDECINE', 'BACH3', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/BACH3/033', 'KAZADI', 'KABONGO', 'SOPHIA', '2001-10-07', 'KINSHASA', 'F', 'sophia.kazadi.033@gmail.com'),
    ('DROIT', 'L2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L2/034', 'MBUYI', 'MUTOMBO', 'JEAN', '2002-11-08', 'LUBUMBASHI', 'M', 'jean.mbuyi.034@gmail.com'),
    ('THEOLOGIE', 'L2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L2/035', 'TSHIBANGU', 'MBUYI', 'GRACE', '2003-12-09', 'KANANGA', 'F', 'grace.tshibangu.035@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/036', 'KABUYA', 'KALONJI', 'JONATHAN', '2004-01-10', 'MATADI', 'M', 'jonathan.kabuya.036@gmail.com'),
    ('FASE', 'L3', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L3/037', 'KANDA', 'KAMBALE', 'SARAH', '2005-02-11', 'MBUJI-MAYI', 'F', 'sarah.kanda.037@gmail.com'),
    ('MEDECINE', 'D4', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/D4/038', 'MALU', 'KASONGO', 'CEDRIC', '2006-03-12', 'KISANGANI', 'M', 'cedric.malu.038@gmail.com'),
    ('DROIT', 'L3', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L3/039', 'KABONGO', 'ILUNGA', 'CHRISTELLE', '2007-04-13', 'KIKWIT', 'F', 'christelle.kabongo.039@gmail.com'),
    ('THEOLOGIE', 'L3', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L3/040', 'NGOY', 'LUKUSA', 'CHRISTIAN', '1998-05-14', 'GOMA', 'M', 'christian.ngoy.040@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/041', 'LUNDA', 'KANDA', 'FAVEUR', '1999-06-15', 'KINSHASA', 'F', 'faveur.lunda.041@gmail.com'),
    ('FASE', 'M1', 'FINANCE', 'FINANCE', 'UPC/FASE/M1/042', 'KIKASA', 'MULUMBA', 'MOISE', '2000-07-16', 'LUBUMBASHI', 'M', 'moise.kikasa.042@gmail.com'),
    ('MEDECINE', 'G0', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/G0/043', 'MAVINGA', 'MBALA', 'CLAUDIA', '2001-08-17', 'KANANGA', 'F', 'claudia.mavinga.043@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/M1/044', 'KABASELE', 'NTUMBA', 'PRINCE', '2002-09-18', 'MATADI', 'M', 'prince.kabasele.044@gmail.com'),
    ('THEOLOGIE', 'M1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/M1/045', 'MULUMBA', 'MUKENDI', 'RUTH', '2003-10-19', 'MBUJI-MAYI', 'F', 'ruth.mulumba.045@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/046', 'KAPINGA', 'KAZADI', 'JUNIOR', '2004-11-20', 'KISANGANI', 'M', 'junior.kapinga.046@gmail.com'),
    ('FASE', 'M2', 'GESTION', 'GESTION', 'UPC/FASE/M2/047', 'KANIKI', 'KALALA', 'DANIELLA', '2005-12-21', 'KIKWIT', 'F', 'daniella.kaniki.047@gmail.com'),
    ('MEDECINE', 'L1', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/L1/048', 'TSHIAMALA', 'TSHILOMBO', 'EMMANUEL', '2006-01-22', 'GOMA', 'M', 'emmanuel.tshiamala.048@gmail.com'),
    ('DROIT', 'M2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M2/049', 'KABAMBA', 'KABONGO', 'SOPHIA', '2007-02-23', 'KINSHASA', 'F', 'sophia.kabamba.049@gmail.com'),
    ('THEOLOGIE', 'M2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M2/050', 'ILUNGA', 'MUTOMBO', 'JEAN', '1998-03-24', 'LUBUMBASHI', 'M', 'jean.ilunga.050@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/051', 'TSHIMANGA', 'MBUYI', 'GRACE', '1999-04-25', 'KANANGA', 'F', 'grace.tshimanga.051@gmail.com'),
    ('FASE', 'L1', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L1/052', 'MUTOMBO', 'KALONJI', 'JONATHAN', '2000-05-26', 'MATADI', 'M', 'jonathan.mutombo.052@gmail.com'),
    ('MEDECINE', 'L2', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/L2/053', 'KALONJI', 'KAMBALE', 'SARAH', '2001-06-27', 'MBUJI-MAYI', 'F', 'sarah.kalonji.053@gmail.com'),
    ('DROIT', 'L1', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L1/054', 'KASONGO', 'KASONGO', 'CEDRIC', '2002-07-01', 'KISANGANI', 'M', 'cedric.kasongo.054@gmail.com'),
    ('THEOLOGIE', 'L1', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L1/055', 'LUKUSA', 'ILUNGA', 'CHRISTELLE', '2003-08-02', 'KIKWIT', 'F', 'christelle.lukusa.055@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/056', 'MUKENDI', 'LUKUSA', 'CHRISTIAN', '2004-09-03', 'GOMA', 'M', 'christian.mukendi.056@gmail.com'),
    ('FASE', 'L2', 'FINANCE', 'FINANCE', 'UPC/FASE/L2/057', 'KAZADI', 'KANDA', 'FAVEUR', '2005-10-04', 'KINSHASA', 'F', 'faveur.kazadi.057@gmail.com'),
    ('MEDECINE', 'L3', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/L3/058', 'MBUYI', 'MULUMBA', 'MOISE', '2006-11-05', 'LUBUMBASHI', 'M', 'moise.mbuyi.058@gmail.com'),
    ('DROIT', 'L2', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L2/059', 'TSHIBANGU', 'MBALA', 'CLAUDIA', '2007-12-06', 'KANANGA', 'F', 'claudia.tshibangu.059@gmail.com'),
    ('THEOLOGIE', 'L2', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L2/060', 'KABUYA', 'NTUMBA', 'PRINCE', '1998-01-07', 'MATADI', 'M', 'prince.kabuya.060@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/061', 'KANDA', 'MUKENDI', 'RUTH', '1999-02-08', 'MBUJI-MAYI', 'F', 'ruth.kanda.061@gmail.com'),
    ('FASE', 'L3', 'GESTION', 'GESTION', 'UPC/FASE/L3/062', 'MALU', 'KAZADI', 'JUNIOR', '2000-03-09', 'KISANGANI', 'M', 'junior.malu.062@gmail.com'),
    ('MEDECINE', 'PR_BACH1', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/PR_BACH1/063', 'KABONGO', 'KALALA', 'DANIELLA', '2001-04-10', 'KIKWIT', 'F', 'daniella.kabongo.063@gmail.com'),
    ('DROIT', 'L3', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L3/064', 'NGOY', 'TSHILOMBO', 'EMMANUEL', '2002-05-11', 'GOMA', 'M', 'emmanuel.ngoy.064@gmail.com'),
    ('THEOLOGIE', 'L3', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L3/065', 'LUNDA', 'KABONGO', 'SOPHIA', '2003-06-12', 'KINSHASA', 'F', 'sophia.lunda.065@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/066', 'KIKASA', 'MUTOMBO', 'JEAN', '2004-07-13', 'LUBUMBASHI', 'M', 'jean.kikasa.066@gmail.com'),
    ('FASE', 'M1', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/M1/067', 'MAVINGA', 'MBUYI', 'GRACE', '2005-08-14', 'KANANGA', 'F', 'grace.mavinga.067@gmail.com'),
    ('MEDECINE', 'BACH2', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/BACH2/068', 'KABASELE', 'KALONJI', 'JONATHAN', '2006-09-15', 'MATADI', 'M', 'jonathan.kabasele.068@gmail.com'),
    ('DROIT', 'M1', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/M1/069', 'MULUMBA', 'KAMBALE', 'SARAH', '2007-10-16', 'MBUJI-MAYI', 'F', 'sarah.mulumba.069@gmail.com'),
    ('THEOLOGIE', 'M1', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/M1/070', 'KAPINGA', 'KASONGO', 'CEDRIC', '1998-11-17', 'KISANGANI', 'M', 'cedric.kapinga.070@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/071', 'KANIKI', 'ILUNGA', 'CHRISTELLE', '1999-12-18', 'KIKWIT', 'F', 'christelle.kaniki.071@gmail.com'),
    ('FASE', 'M2', 'FINANCE', 'FINANCE', 'UPC/FASE/M2/072', 'TSHIAMALA', 'LUKUSA', 'CHRISTIAN', '2000-01-19', 'GOMA', 'M', 'christian.tshiamala.072@gmail.com'),
    ('MEDECINE', 'BACH3', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/BACH3/073', 'KABAMBA', 'KANDA', 'FAVEUR', '2001-02-20', 'KINSHASA', 'F', 'faveur.kabamba.073@gmail.com'),
    ('DROIT', 'M2', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/M2/074', 'ILUNGA', 'MULUMBA', 'MOISE', '2002-03-21', 'LUBUMBASHI', 'M', 'moise.ilunga.074@gmail.com'),
    ('THEOLOGIE', 'M2', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/M2/075', 'TSHIMANGA', 'MBALA', 'CLAUDIA', '2003-04-22', 'KANANGA', 'F', 'claudia.tshimanga.075@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/076', 'MUTOMBO', 'NTUMBA', 'PRINCE', '2004-05-23', 'MATADI', 'M', 'prince.mutombo.076@gmail.com'),
    ('FASE', 'L1', 'GESTION', 'GESTION', 'UPC/FASE/L1/077', 'KALONJI', 'MUKENDI', 'RUTH', '2005-06-24', 'MBUJI-MAYI', 'F', 'ruth.kalonji.077@gmail.com'),
    ('MEDECINE', 'D4', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/D4/078', 'KASONGO', 'KAZADI', 'JUNIOR', '2006-07-25', 'KISANGANI', 'M', 'junior.kasongo.078@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L1/079', 'LUKUSA', 'KALALA', 'DANIELLA', '2007-08-26', 'KIKWIT', 'F', 'daniella.lukusa.079@gmail.com'),
    ('THEOLOGIE', 'L1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L1/080', 'MUKENDI', 'TSHILOMBO', 'EMMANUEL', '1998-09-27', 'GOMA', 'M', 'emmanuel.mukendi.080@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/081', 'KAZADI', 'KABONGO', 'SOPHIA', '1999-10-01', 'KINSHASA', 'F', 'sophia.kazadi.081@gmail.com'),
    ('FASE', 'L2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L2/082', 'MBUYI', 'MUTOMBO', 'JEAN', '2000-11-02', 'LUBUMBASHI', 'M', 'jean.mbuyi.082@gmail.com'),
    ('MEDECINE', 'G0', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/G0/083', 'TSHIBANGU', 'MBUYI', 'GRACE', '2001-12-03', 'KANANGA', 'F', 'grace.tshibangu.083@gmail.com'),
    ('DROIT', 'L2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L2/084', 'KABUYA', 'KALONJI', 'JONATHAN', '2002-01-04', 'MATADI', 'M', 'jonathan.kabuya.084@gmail.com'),
    ('THEOLOGIE', 'L2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L2/085', 'KANDA', 'KAMBALE', 'SARAH', '2003-02-05', 'MBUJI-MAYI', 'F', 'sarah.kanda.085@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/086', 'MALU', 'KASONGO', 'CEDRIC', '2004-03-06', 'KISANGANI', 'M', 'cedric.malu.086@gmail.com'),
    ('FASE', 'L3', 'FINANCE', 'FINANCE', 'UPC/FASE/L3/087', 'KABONGO', 'ILUNGA', 'CHRISTELLE', '2005-04-07', 'KIKWIT', 'F', 'christelle.kabongo.087@gmail.com'),
    ('MEDECINE', 'L1', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/L1/088', 'NGOY', 'LUKUSA', 'CHRISTIAN', '2006-05-08', 'GOMA', 'M', 'christian.ngoy.088@gmail.com'),
    ('DROIT', 'L3', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L3/089', 'LUNDA', 'KANDA', 'FAVEUR', '2007-06-09', 'KINSHASA', 'F', 'faveur.lunda.089@gmail.com'),
    ('THEOLOGIE', 'L3', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L3/090', 'KIKASA', 'MULUMBA', 'MOISE', '1998-07-10', 'LUBUMBASHI', 'M', 'moise.kikasa.090@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/091', 'MAVINGA', 'MBALA', 'CLAUDIA', '1999-08-11', 'KANANGA', 'F', 'claudia.mavinga.091@gmail.com'),
    ('FASE', 'M1', 'GESTION', 'GESTION', 'UPC/FASE/M1/092', 'KABASELE', 'NTUMBA', 'PRINCE', '2000-09-12', 'MATADI', 'M', 'prince.kabasele.092@gmail.com'),
    ('MEDECINE', 'L2', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/L2/093', 'MULUMBA', 'MUKENDI', 'RUTH', '2001-10-13', 'MBUJI-MAYI', 'F', 'ruth.mulumba.093@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M1/094', 'KAPINGA', 'KAZADI', 'JUNIOR', '2002-11-14', 'KISANGANI', 'M', 'junior.kapinga.094@gmail.com'),
    ('THEOLOGIE', 'M1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M1/095', 'KANIKI', 'KALALA', 'DANIELLA', '2003-12-15', 'KIKWIT', 'F', 'daniella.kaniki.095@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/096', 'TSHIAMALA', 'TSHILOMBO', 'EMMANUEL', '2004-01-16', 'GOMA', 'M', 'emmanuel.tshiamala.096@gmail.com'),
    ('FASE', 'M2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/M2/097', 'KABAMBA', 'KABONGO', 'SOPHIA', '2005-02-17', 'KINSHASA', 'F', 'sophia.kabamba.097@gmail.com'),
    ('MEDECINE', 'L3', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/L3/098', 'ILUNGA', 'MUTOMBO', 'JEAN', '2006-03-18', 'LUBUMBASHI', 'M', 'jean.ilunga.098@gmail.com'),
    ('DROIT', 'M2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/M2/099', 'TSHIMANGA', 'MBUYI', 'GRACE', '2007-04-19', 'KANANGA', 'F', 'grace.tshimanga.099@gmail.com'),
    ('THEOLOGIE', 'M2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/M2/100', 'MUTOMBO', 'KALONJI', 'JONATHAN', '1998-05-20', 'MATADI', 'M', 'jonathan.mutombo.100@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/101', 'KALONJI', 'KAMBALE', 'SARAH', '1999-06-21', 'MBUJI-MAYI', 'F', 'sarah.kalonji.101@gmail.com'),
    ('FASE', 'L1', 'FINANCE', 'FINANCE', 'UPC/FASE/L1/102', 'KASONGO', 'KASONGO', 'CEDRIC', '2000-07-22', 'KISANGANI', 'M', 'cedric.kasongo.102@gmail.com'),
    ('MEDECINE', 'PR_BACH1', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/PR_BACH1/103', 'LUKUSA', 'ILUNGA', 'CHRISTELLE', '2001-08-23', 'KIKWIT', 'F', 'christelle.lukusa.103@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L1/104', 'MUKENDI', 'LUKUSA', 'CHRISTIAN', '2002-09-24', 'GOMA', 'M', 'christian.mukendi.104@gmail.com'),
    ('THEOLOGIE', 'L1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L1/105', 'KAZADI', 'KANDA', 'FAVEUR', '2003-10-25', 'KINSHASA', 'F', 'faveur.kazadi.105@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/106', 'MBUYI', 'MULUMBA', 'MOISE', '2004-11-26', 'LUBUMBASHI', 'M', 'moise.mbuyi.106@gmail.com'),
    ('FASE', 'L2', 'GESTION', 'GESTION', 'UPC/FASE/L2/107', 'TSHIBANGU', 'MBALA', 'CLAUDIA', '2005-12-27', 'KANANGA', 'F', 'claudia.tshibangu.107@gmail.com'),
    ('MEDECINE', 'BACH2', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/BACH2/108', 'KABUYA', 'NTUMBA', 'PRINCE', '2006-01-01', 'MATADI', 'M', 'prince.kabuya.108@gmail.com'),
    ('DROIT', 'L2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L2/109', 'KANDA', 'MUKENDI', 'RUTH', '2007-02-02', 'MBUJI-MAYI', 'F', 'ruth.kanda.109@gmail.com'),
    ('THEOLOGIE', 'L2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L2/110', 'MALU', 'KAZADI', 'JUNIOR', '1998-03-03', 'KISANGANI', 'M', 'junior.malu.110@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/111', 'KABONGO', 'KALALA', 'DANIELLA', '1999-04-04', 'KIKWIT', 'F', 'daniella.kabongo.111@gmail.com'),
    ('FASE', 'L3', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L3/112', 'NGOY', 'TSHILOMBO', 'EMMANUEL', '2000-05-05', 'GOMA', 'M', 'emmanuel.ngoy.112@gmail.com'),
    ('MEDECINE', 'BACH3', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/BACH3/113', 'LUNDA', 'KABONGO', 'SOPHIA', '2001-06-06', 'KINSHASA', 'F', 'sophia.lunda.113@gmail.com'),
    ('DROIT', 'L3', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L3/114', 'KIKASA', 'MUTOMBO', 'JEAN', '2002-07-07', 'LUBUMBASHI', 'M', 'jean.kikasa.114@gmail.com'),
    ('THEOLOGIE', 'L3', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L3/115', 'MAVINGA', 'MBUYI', 'GRACE', '2003-08-08', 'KANANGA', 'F', 'grace.mavinga.115@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/116', 'KABASELE', 'KALONJI', 'JONATHAN', '2004-09-09', 'MATADI', 'M', 'jonathan.kabasele.116@gmail.com'),
    ('FASE', 'M1', 'FINANCE', 'FINANCE', 'UPC/FASE/M1/117', 'MULUMBA', 'KAMBALE', 'SARAH', '2005-10-10', 'MBUJI-MAYI', 'F', 'sarah.mulumba.117@gmail.com'),
    ('MEDECINE', 'D4', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/D4/118', 'KAPINGA', 'KASONGO', 'CEDRIC', '2006-11-11', 'KISANGANI', 'M', 'cedric.kapinga.118@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/M1/119', 'KANIKI', 'ILUNGA', 'CHRISTELLE', '2007-12-12', 'KIKWIT', 'F', 'christelle.kaniki.119@gmail.com'),
    ('THEOLOGIE', 'M1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/M1/120', 'TSHIAMALA', 'LUKUSA', 'CHRISTIAN', '1998-01-13', 'GOMA', 'M', 'christian.tshiamala.120@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/121', 'KABAMBA', 'KANDA', 'FAVEUR', '1999-02-14', 'KINSHASA', 'F', 'faveur.kabamba.121@gmail.com'),
    ('FASE', 'M2', 'GESTION', 'GESTION', 'UPC/FASE/M2/122', 'ILUNGA', 'MULUMBA', 'MOISE', '2000-03-15', 'LUBUMBASHI', 'M', 'moise.ilunga.122@gmail.com'),
    ('MEDECINE', 'G0', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/G0/123', 'TSHIMANGA', 'MBALA', 'CLAUDIA', '2001-04-16', 'KANANGA', 'F', 'claudia.tshimanga.123@gmail.com'),
    ('DROIT', 'M2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M2/124', 'MUTOMBO', 'NTUMBA', 'PRINCE', '2002-05-17', 'MATADI', 'M', 'prince.mutombo.124@gmail.com'),
    ('THEOLOGIE', 'M2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M2/125', 'KALONJI', 'MUKENDI', 'RUTH', '2003-06-18', 'MBUJI-MAYI', 'F', 'ruth.kalonji.125@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/126', 'KASONGO', 'KAZADI', 'JUNIOR', '2004-07-19', 'KISANGANI', 'M', 'junior.kasongo.126@gmail.com'),
    ('FASE', 'L1', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L1/127', 'LUKUSA', 'KALALA', 'DANIELLA', '2005-08-20', 'KIKWIT', 'F', 'daniella.lukusa.127@gmail.com'),
    ('MEDECINE', 'L1', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/L1/128', 'MUKENDI', 'TSHILOMBO', 'EMMANUEL', '2006-09-21', 'GOMA', 'M', 'emmanuel.mukendi.128@gmail.com'),
    ('DROIT', 'L1', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L1/129', 'KAZADI', 'KABONGO', 'SOPHIA', '2007-10-22', 'KINSHASA', 'F', 'sophia.kazadi.129@gmail.com'),
    ('THEOLOGIE', 'L1', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L1/130', 'MBUYI', 'MUTOMBO', 'JEAN', '1998-11-23', 'LUBUMBASHI', 'M', 'jean.mbuyi.130@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/131', 'TSHIBANGU', 'MBUYI', 'GRACE', '1999-12-24', 'KANANGA', 'F', 'grace.tshibangu.131@gmail.com'),
    ('FASE', 'L2', 'FINANCE', 'FINANCE', 'UPC/FASE/L2/132', 'KABUYA', 'KALONJI', 'JONATHAN', '2000-01-25', 'MATADI', 'M', 'jonathan.kabuya.132@gmail.com'),
    ('MEDECINE', 'L2', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/L2/133', 'KANDA', 'KAMBALE', 'SARAH', '2001-02-26', 'MBUJI-MAYI', 'F', 'sarah.kanda.133@gmail.com'),
    ('DROIT', 'L2', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L2/134', 'MALU', 'KASONGO', 'CEDRIC', '2002-03-27', 'KISANGANI', 'M', 'cedric.malu.134@gmail.com'),
    ('THEOLOGIE', 'L2', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L2/135', 'KABONGO', 'ILUNGA', 'CHRISTELLE', '2003-04-01', 'KIKWIT', 'F', 'christelle.kabongo.135@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/136', 'NGOY', 'LUKUSA', 'CHRISTIAN', '2004-05-02', 'GOMA', 'M', 'christian.ngoy.136@gmail.com'),
    ('FASE', 'L3', 'GESTION', 'GESTION', 'UPC/FASE/L3/137', 'LUNDA', 'KANDA', 'FAVEUR', '2005-06-03', 'KINSHASA', 'F', 'faveur.lunda.137@gmail.com'),
    ('MEDECINE', 'L3', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/L3/138', 'KIKASA', 'MULUMBA', 'MOISE', '2006-07-04', 'LUBUMBASHI', 'M', 'moise.kikasa.138@gmail.com'),
    ('DROIT', 'L3', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L3/139', 'MAVINGA', 'MBALA', 'CLAUDIA', '2007-08-05', 'KANANGA', 'F', 'claudia.mavinga.139@gmail.com'),
    ('THEOLOGIE', 'L3', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L3/140', 'KABASELE', 'NTUMBA', 'PRINCE', '1998-09-06', 'MATADI', 'M', 'prince.kabasele.140@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/141', 'MULUMBA', 'MUKENDI', 'RUTH', '1999-10-07', 'MBUJI-MAYI', 'F', 'ruth.mulumba.141@gmail.com'),
    ('FASE', 'M1', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/M1/142', 'KAPINGA', 'KAZADI', 'JUNIOR', '2000-11-08', 'KISANGANI', 'M', 'junior.kapinga.142@gmail.com'),
    ('MEDECINE', 'PR_BACH1', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/PR_BACH1/143', 'KANIKI', 'KALALA', 'DANIELLA', '2001-12-09', 'KIKWIT', 'F', 'daniella.kaniki.143@gmail.com'),
    ('DROIT', 'M1', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/M1/144', 'TSHIAMALA', 'TSHILOMBO', 'EMMANUEL', '2002-01-10', 'GOMA', 'M', 'emmanuel.tshiamala.144@gmail.com'),
    ('THEOLOGIE', 'M1', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/M1/145', 'KABAMBA', 'KABONGO', 'SOPHIA', '2003-02-11', 'KINSHASA', 'F', 'sophia.kabamba.145@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/146', 'ILUNGA', 'MUTOMBO', 'JEAN', '2004-03-12', 'LUBUMBASHI', 'M', 'jean.ilunga.146@gmail.com'),
    ('FASE', 'M2', 'FINANCE', 'FINANCE', 'UPC/FASE/M2/147', 'TSHIMANGA', 'MBUYI', 'GRACE', '2005-04-13', 'KANANGA', 'F', 'grace.tshimanga.147@gmail.com'),
    ('MEDECINE', 'BACH2', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/BACH2/148', 'MUTOMBO', 'KALONJI', 'JONATHAN', '2006-05-14', 'MATADI', 'M', 'jonathan.mutombo.148@gmail.com'),
    ('DROIT', 'M2', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/M2/149', 'KALONJI', 'KAMBALE', 'SARAH', '2007-06-15', 'MBUJI-MAYI', 'F', 'sarah.kalonji.149@gmail.com'),
    ('THEOLOGIE', 'M2', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/M2/150', 'KASONGO', 'KASONGO', 'CEDRIC', '1998-07-16', 'KISANGANI', 'M', 'cedric.kasongo.150@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/151', 'LUKUSA', 'ILUNGA', 'CHRISTELLE', '1999-08-17', 'KIKWIT', 'F', 'christelle.lukusa.151@gmail.com'),
    ('FASE', 'L1', 'GESTION', 'GESTION', 'UPC/FASE/L1/152', 'MUKENDI', 'LUKUSA', 'CHRISTIAN', '2000-09-18', 'GOMA', 'M', 'christian.mukendi.152@gmail.com'),
    ('MEDECINE', 'BACH3', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/BACH3/153', 'KAZADI', 'KANDA', 'FAVEUR', '2001-10-19', 'KINSHASA', 'F', 'faveur.kazadi.153@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L1/154', 'MBUYI', 'MULUMBA', 'MOISE', '2002-11-20', 'LUBUMBASHI', 'M', 'moise.mbuyi.154@gmail.com'),
    ('THEOLOGIE', 'L1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L1/155', 'TSHIBANGU', 'MBALA', 'CLAUDIA', '2003-12-21', 'KANANGA', 'F', 'claudia.tshibangu.155@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/156', 'KABUYA', 'NTUMBA', 'PRINCE', '2004-01-22', 'MATADI', 'M', 'prince.kabuya.156@gmail.com'),
    ('FASE', 'L2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L2/157', 'KANDA', 'MUKENDI', 'RUTH', '2005-02-23', 'MBUJI-MAYI', 'F', 'ruth.kanda.157@gmail.com'),
    ('MEDECINE', 'D4', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/D4/158', 'MALU', 'KAZADI', 'JUNIOR', '2006-03-24', 'KISANGANI', 'M', 'junior.malu.158@gmail.com'),
    ('DROIT', 'L2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L2/159', 'KABONGO', 'KALALA', 'DANIELLA', '2007-04-25', 'KIKWIT', 'F', 'daniella.kabongo.159@gmail.com'),
    ('THEOLOGIE', 'L2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L2/160', 'NGOY', 'TSHILOMBO', 'EMMANUEL', '1998-05-26', 'GOMA', 'M', 'emmanuel.ngoy.160@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/161', 'LUNDA', 'KABONGO', 'SOPHIA', '1999-06-27', 'KINSHASA', 'F', 'sophia.lunda.161@gmail.com'),
    ('FASE', 'L3', 'FINANCE', 'FINANCE', 'UPC/FASE/L3/162', 'KIKASA', 'MUTOMBO', 'JEAN', '2000-07-01', 'LUBUMBASHI', 'M', 'jean.kikasa.162@gmail.com'),
    ('MEDECINE', 'G0', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/G0/163', 'MAVINGA', 'MBUYI', 'GRACE', '2001-08-02', 'KANANGA', 'F', 'grace.mavinga.163@gmail.com'),
    ('DROIT', 'L3', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L3/164', 'KABASELE', 'KALONJI', 'JONATHAN', '2002-09-03', 'MATADI', 'M', 'jonathan.kabasele.164@gmail.com'),
    ('THEOLOGIE', 'L3', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L3/165', 'MULUMBA', 'KAMBALE', 'SARAH', '2003-10-04', 'MBUJI-MAYI', 'F', 'sarah.mulumba.165@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/166', 'KAPINGA', 'KASONGO', 'CEDRIC', '2004-11-05', 'KISANGANI', 'M', 'cedric.kapinga.166@gmail.com'),
    ('FASE', 'M1', 'GESTION', 'GESTION', 'UPC/FASE/M1/167', 'KANIKI', 'ILUNGA', 'CHRISTELLE', '2005-12-06', 'KIKWIT', 'F', 'christelle.kaniki.167@gmail.com'),
    ('MEDECINE', 'L1', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/L1/168', 'TSHIAMALA', 'LUKUSA', 'CHRISTIAN', '2006-01-07', 'GOMA', 'M', 'christian.tshiamala.168@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M1/169', 'KABAMBA', 'KANDA', 'FAVEUR', '2007-02-08', 'KINSHASA', 'F', 'faveur.kabamba.169@gmail.com'),
    ('THEOLOGIE', 'M1', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M1/170', 'ILUNGA', 'MULUMBA', 'MOISE', '1998-03-09', 'LUBUMBASHI', 'M', 'moise.ilunga.170@gmail.com'),
    ('FASI', 'M1', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/M1/171', 'TSHIMANGA', 'MBALA', 'CLAUDIA', '1999-04-10', 'KANANGA', 'F', 'claudia.tshimanga.171@gmail.com'),
    ('FASE', 'M2', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/M2/172', 'MUTOMBO', 'NTUMBA', 'PRINCE', '2000-05-11', 'MATADI', 'M', 'prince.mutombo.172@gmail.com'),
    ('MEDECINE', 'L2', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/L2/173', 'KALONJI', 'MUKENDI', 'RUTH', '2001-06-12', 'MBUJI-MAYI', 'F', 'ruth.kalonji.173@gmail.com'),
    ('DROIT', 'M2', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/M2/174', 'KASONGO', 'KAZADI', 'JUNIOR', '2002-07-13', 'KISANGANI', 'M', 'junior.kasongo.174@gmail.com'),
    ('THEOLOGIE', 'M2', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/M2/175', 'LUKUSA', 'KALALA', 'DANIELLA', '2003-08-14', 'KIKWIT', 'F', 'daniella.lukusa.175@gmail.com'),
    ('FASI', 'M2', 'RESEAUX', 'RESEAUX', 'UPC/FASI/M2/176', 'MUKENDI', 'TSHILOMBO', 'EMMANUEL', '2004-09-15', 'GOMA', 'M', 'emmanuel.mukendi.176@gmail.com'),
    ('FASE', 'L1', 'FINANCE', 'FINANCE', 'UPC/FASE/L1/177', 'KAZADI', 'KABONGO', 'SOPHIA', '2005-10-16', 'KINSHASA', 'F', 'sophia.kazadi.177@gmail.com'),
    ('MEDECINE', 'L3', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/L3/178', 'MBUYI', 'MUTOMBO', 'JEAN', '2006-11-17', 'LUBUMBASHI', 'M', 'jean.mbuyi.178@gmail.com'),
    ('DROIT', 'L1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/L1/179', 'TSHIBANGU', 'MBUYI', 'GRACE', '2007-12-18', 'KANANGA', 'F', 'grace.tshibangu.179@gmail.com'),
    ('THEOLOGIE', 'L1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/L1/180', 'KABUYA', 'KALONJI', 'JONATHAN', '1998-01-19', 'MATADI', 'M', 'jonathan.kabuya.180@gmail.com'),
    ('FASI', 'L1', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L1/181', 'KANDA', 'KAMBALE', 'SARAH', '1999-02-20', 'MBUJI-MAYI', 'F', 'sarah.kanda.181@gmail.com'),
    ('FASE', 'L2', 'GESTION', 'GESTION', 'UPC/FASE/L2/182', 'MALU', 'KASONGO', 'CEDRIC', '2000-03-21', 'KISANGANI', 'M', 'cedric.malu.182@gmail.com'),
    ('MEDECINE', 'PR_BACH1', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/PR_BACH1/183', 'KABONGO', 'ILUNGA', 'CHRISTELLE', '2001-04-22', 'KIKWIT', 'F', 'christelle.kabongo.183@gmail.com'),
    ('DROIT', 'L2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/L2/184', 'NGOY', 'LUKUSA', 'CHRISTIAN', '2002-05-23', 'GOMA', 'M', 'christian.ngoy.184@gmail.com'),
    ('THEOLOGIE', 'L2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/L2/185', 'LUNDA', 'KANDA', 'FAVEUR', '2003-06-24', 'KINSHASA', 'F', 'faveur.lunda.185@gmail.com'),
    ('FASI', 'L2', 'SYSTEMES_D_INFORMATION', 'SYSTEMES D INFORMATION', 'UPC/FASI/L2/186', 'KIKASA', 'MULUMBA', 'MOISE', '2004-07-25', 'LUBUMBASHI', 'M', 'moise.kikasa.186@gmail.com'),
    ('FASE', 'L3', 'ECONOMIE', 'ECONOMIE', 'UPC/FASE/L3/187', 'MAVINGA', 'MBALA', 'CLAUDIA', '2005-08-26', 'KANANGA', 'F', 'claudia.mavinga.187@gmail.com'),
    ('MEDECINE', 'BACH2', 'SANTE_PUBLIQUE', 'SANTE PUBLIQUE', 'UPC/MEDECINE/BACH2/188', 'KABASELE', 'NTUMBA', 'PRINCE', '2006-09-27', 'MATADI', 'M', 'prince.kabasele.188@gmail.com'),
    ('DROIT', 'L3', 'DROIT_ECONOMIQUE', 'DROIT ECONOMIQUE', 'UPC/DROIT/L3/189', 'MULUMBA', 'MUKENDI', 'RUTH', '2007-10-01', 'MBUJI-MAYI', 'F', 'ruth.mulumba.189@gmail.com'),
    ('THEOLOGIE', 'L3', 'THEOLOGIE_PASTORALE', 'THEOLOGIE PASTORALE', 'UPC/THEOLOGIE/L3/190', 'KAPINGA', 'KAZADI', 'JUNIOR', '1998-11-02', 'KISANGANI', 'M', 'junior.kapinga.190@gmail.com'),
    ('FASI', 'L3', 'RESEAUX', 'RESEAUX', 'UPC/FASI/L3/191', 'KANIKI', 'KALALA', 'DANIELLA', '1999-12-03', 'KIKWIT', 'F', 'daniella.kaniki.191@gmail.com'),
    ('FASE', 'M1', 'FINANCE', 'FINANCE', 'UPC/FASE/M1/192', 'TSHIAMALA', 'TSHILOMBO', 'EMMANUEL', '2000-01-04', 'GOMA', 'M', 'emmanuel.tshiamala.192@gmail.com'),
    ('MEDECINE', 'BACH3', 'MEDECINE_GENERALE', 'MEDECINE GENERALE', 'UPC/MEDECINE/BACH3/193', 'KABAMBA', 'KABONGO', 'SOPHIA', '2001-02-05', 'KINSHASA', 'F', 'sophia.kabamba.193@gmail.com'),
    ('DROIT', 'M1', 'DROIT_PUBLIC', 'DROIT PUBLIC', 'UPC/DROIT/M1/194', 'ILUNGA', 'MUTOMBO', 'JEAN', '2002-03-06', 'LUBUMBASHI', 'M', 'jean.ilunga.194@gmail.com'),
    ('THEOLOGIE', 'M1', 'HISTOIRE_DE_L_EGLISE', 'HISTOIRE DE L EGLISE', 'UPC/THEOLOGIE/M1/195', 'TSHIMANGA', 'MBUYI', 'GRACE', '2003-04-07', 'KANANGA', 'F', 'grace.tshimanga.195@gmail.com'),
    ('FASI', 'L4', 'GENIE_LOGICIEL', 'GENIE LOGICIEL', 'UPC/FASI/L4/196', 'MUTOMBO', 'KALONJI', 'JONATHAN', '2004-05-08', 'MATADI', 'M', 'jonathan.mutombo.196@gmail.com'),
    ('FASE', 'M2', 'GESTION', 'GESTION', 'UPC/FASE/M2/197', 'KALONJI', 'KAMBALE', 'SARAH', '2005-06-09', 'MBUJI-MAYI', 'F', 'sarah.kalonji.197@gmail.com'),
    ('MEDECINE', 'D4', 'SCIENCES_BIOMEDICALES', 'SCIENCES BIOMEDICALES', 'UPC/MEDECINE/D4/198', 'KASONGO', 'KASONGO', 'CEDRIC', '2006-07-10', 'KISANGANI', 'M', 'cedric.kasongo.198@gmail.com'),
    ('DROIT', 'M2', 'DROIT_PRIVE', 'DROIT PRIVE', 'UPC/DROIT/M2/199', 'LUKUSA', 'ILUNGA', 'CHRISTELLE', '2007-08-11', 'KIKWIT', 'F', 'christelle.lukusa.199@gmail.com'),
    ('THEOLOGIE', 'M2', 'SCIENCES_BIBLIQUES', 'SCIENCES BIBLIQUES', 'UPC/THEOLOGIE/M2/200', 'MUKENDI', 'LUKUSA', 'CHRISTIAN', '1998-09-12', 'GOMA', 'M', 'christian.mukendi.200@gmail.com');

INSERT INTO departements (faculte_id, code, nom, actif, cree_le, modifie_le)
SELECT DISTINCT
    f.id,
    d.departement_code,
    d.departement_nom,
    TRUE,
    NOW(),
    NOW()
FROM temp_etudiants_demo_vote_upc d
INNER JOIN facultes f ON f.code = d.faculte_code
ON CONFLICT (faculte_id, code) DO UPDATE
SET nom = EXCLUDED.nom,
    actif = TRUE,
    modifie_le = NOW();

WITH
super_admin AS (
    SELECT u.id
    FROM utilisateurs u
    INNER JOIN roles r ON r.id = u.role_id
    WHERE r.code = 'super_administrateur'
    ORDER BY u.id
    LIMIT 1
)
INSERT INTO etudiants (
    faculte_id,
    departement_id,
    promotion_id,
    nom,
    post_nom,
    prenom,
    date_naissance,
    lieu_naissance,
    sexe,
    email,
    matricule,
    statut,
    source_creation,
    cree_par,
    cree_le,
    modifie_le
)
SELECT
    f.id,
    dep.id,
    p.id,
    d.nom,
    d.post_nom,
    d.prenom,
    d.date_naissance::date,
    d.lieu_naissance,
    d.sexe,
    LOWER(d.email),
    d.matricule,
    'non_active',
    'import_excel',
    sa.id,
    NOW(),
    NOW()
FROM temp_etudiants_demo_vote_upc d
INNER JOIN facultes f ON f.code = d.faculte_code
INNER JOIN promotions p ON p.faculte_id = f.id AND p.code = d.promotion_code
INNER JOIN departements dep ON dep.faculte_id = f.id AND dep.code = d.departement_code
LEFT JOIN super_admin sa ON TRUE
ON CONFLICT DO NOTHING;

COMMIT;
